package com.tatasky.binge.analytics

// Super Properties
const val SID = "SID"
const val RMN = "RMN"
const val PROFILE_ID = "PROFILE-ID"
const val TP_RMN = "TP-RMN"
const val EMAIL = "EMAIL"
const val FIRE_TV = "FIRE-TV"
const val FTV_ELIGIBLE = "FTV-ELIGIBLE"
const val ATV = "ATV"
const val SUBSCRIBED = "SUBSCRIBED"
const val DATE_OF_SUBSCRIPTION = "DATE-OF-SUBSCRIPTION"
const val LOGGED_IN_DEVICE_COUNT = "LOGGED-IN-DEVICE-COUNT"
const val BINGE_ACCOUNT_COUNT = "BINGE-ACCOUNTS-COUNT"
const val FIRST_TIME_LOGIN = "FIRST-TIME-LOGIN"
const val FIRST_TIME = "FIRST-TIME"
const val TIMESTAMP = "TIMESTAMP"
const val NAME = "NAME"
const val FNAME = "FIRST-NAME"
const val LNAME = "LAST-NAME"
const val ANALYTICS_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss'Z'"
const val HH_MM_WITH_MERIDIAN_TIME_FORMAT = "hh:mm a"
const val HH_MM_WITHOUT_MERIDIAN_TIME_FORMAT = "hh:mm"
const val FREE_TRIAL = "FREE-TRIAL"
const val PACK_NAME = "PACK-NAME"
const val PACK_TYPE = "PACK-TYPE"
const val PACK_PRICE = "PACK-PRICE"
const val UPGRADED_PACK_PRICE = "UPGRADED-PACK-PRICE"
const val SUBSCRIPTION_TYPE  = "SUBSCRIPTION-TYPE"
const val FREE_TRIAL_ELIGIBLE = "FREE-TRIAL-ELIGIBLE"
const val PACK_START_DATE = "PACK-START-DATE"
const val PACK_END_DATE = "PACK-END-DATE"
const val RENEWAL_DUE = "RENEWAL-DUE"
const val LAST_USED_AT = "LAST-USED-AT"
const val PACK_RENEWAL_DATE = "PACK-RENEWAL-DATE"
const val BURN_RATE_TYPE  = "BURN-RATE-TYPE"
const val ANDROID_APP_VERSION  = "ANDROID-APP-VERSION"
const val ANDROID_APP_VERSION_NAME = "ANDROID-APP-VERSION-NAME"
const val ORDERED_FTV  = "ORDERED-FTV"
const val FTV_ORDER_TYPE = "FTV-ORDER-TYPE"
const val SI_PAYMENT_MODE = "SI_PAYMENT_MODE"
const val RECURRING_PAYMENT = "RECURRING_PAYMENT"
const val ANONYMOUS_ID = "ANONYMOUS-ID"
const val SUBSCRIPTION_ID = "SUBSCRIPTION-ID"
const val PLATFORM = "PLATFORM"
const val MOE_PLATFORM = "Freemium_Android"
const val DEVICE_TYPE = "Android"
const val DEVICE_TYPE_TABLET = "ANDROID-TABLET"
const val PLATFORM_ANDROID = "Android"
const val PLATFORM_ANDROID_TABLET = "ANDROID-TABLET"
const val PLATFORM_ANDROID_CAPS = "ANDROID"

const val START_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss"
const val END_DATE_FORMAT = "dd/MM/yyyy"
const val DEAFULT_DATE_FORMAT_FROM_BE = "yyyy-MM-dd hh:mm:ss"

const val TS_SID = "TS-SID"
const val C_ID = "C-ID"
const val STACK = "STACK"
const val ATV_SERIAL_NUMBER = "ATV-SERIAL-NUMBER"
const val FS = "FS"
const val FS_SERIAL_NUMBER = "FS-SERIAL-NUMBER"
const val DEVICE_1 = "DEVICE-1"
const val DEVICE_2 = "DEVICE-2"
const val DEVICE_3 = "DEVICE-3"
const val DEVICE_4 = "DEVICE-4"
const val LAST_USED_DEVICE = "LAST-USED-DEVICE"
const val LAST_PACK_TYPE = "LAST-PACK-TYPE"
const val LAST_PACK_PRICE = "LAST-PACK-PRICE"
const val LAST_PACK_NAME = "LAST-PACK-NAME"
const val LAST_BILLING_TYPE = "LAST-BILLING-TYPE"
const val RENEWAL_DUE_DATE = "RENEWAL-DUE-DATE"
const val DAYS_SINCE_LAST_USAGE = "DAYS-SINCE-LAST-USAGE"
const val LAST_APP_USAGE_DATE = "LAST-APP-USAGE-DATE"
const val NOTIFICATION_ENABLED = "NOTIFICATIONS-ENABLED"
const val TOTAL_PAID_PACK_RENEWALS = "TOTAL-PAID-PACK-RENEWALS"
const val FIRST_LOGIN_DATE = "FIRST-LOGIN-DATE"
const val FIRST_PACK_SUBSCRIPTION_DATE = "FIRST-PACK-SUBSCRIPTION-DATE"
const val FIRST_PAID_PACK_SUBSCRIPTION_DATE = "FIRST-PAID-PACK-SUBSCRIPTION-DATE"
const val DEVICE_USED_IN_LAST_DAYS = "DEVICE-USED-IN-LAST-DAYS"
const val LAST_LOGOUT_DATE = "LAST-LOGOUT-DATE"
const val TOTAL_WATCH_HOURS_LAST_DAYS = "TOTAL-WATCH-HOURS-LAST-DAYS"
const val TOTAL_WATCH_HOURS_LIFETIME = "TOTAL-WATCH-HOURS-LIFETIME"
const val FREE_TRIAL_TAKEN = "FREE-TRIAL-TAKEN"
const val GENDER = "GENDER"
const val AGE = "AGE"
const val PROFILE_NAME = "PROFILE-NAME"
const val TYPE_OF_SUBSCRIBER = "TYPE-OF-SUBSCRIBER"
const val FIRST_APP_DOWNLOAD_DATE = "FIRST-APP-DOWNLOAD-DATE"
const val DOWNLOAD_SOURCE = "DOWNLOAD-SOURCE"
const val CITY = "CITY"
const val STATE = "STATE"
const val COUNTRY = "COUNTRY"
const val APP_UPTIME = "APP-UPTIME"
const val APP_SESSION_TIME = "APP-SESSION-TIME"
const val DAYS_USING_AS_NON_LOGGED_IN_USER = "DAYS-USING-AS-NON-LOGGED-IN-USER"
const val DAYS_REMAINING_IN_PAID_SUBSCRIPTION = "DAYS-REMAINING-IN-PAID-SUBSCRIPTION"
const val WATCH_DURATION = "WATCH-DURATION"
const val DEVICE_ID = "DEVICE-ID"
const val MIXPANEL_ID = "MIXPANEL-ID"
const val AQUISITION_SOURCE="ACQUISITION-SOURCE"
const val FIBER="Fiber"

///////===============clevertap starts==============///////////
const val IDENTITY = "Identity"
const val EMAIL_CLEVER = "Email"
const val NAME_CLEVER = "Name"
const val PHONE_CLEVER = "Phone"
const val TEST_SID = "987678666"
const val CLEVERTAP_LOG = "CLEVERTAP_ANALYTICS"
///////==============clevertap ends================/////////////


/*SID





OS Details – Type, Version

DEVICE DETAILS = Manufacturer, Version

Number of Content Played Based on Genre/Content Type

Duration of Content Played Based on Genre/Content Type

FireStick User - YES/NO

ATV User - YES/NO*/

const val YES = "YES"
const val NO = "NO"
const val DOWN = "DOWN"
const val UP = "UP"
const val PROFILE_REGULAR = "Regular"
const val COMMON_ERROR_MSG ="Something Went Wrong"

/*Keyboard states*/
const val PARA_CLOSED = "CLOSED"
const val PARA_OPEN = "OPEN"


/*Splash Screen Events*/
const val EVENT_APP_LAUNCH = "APP-LAUNCH"    //done
const val EVENT_BINGE_APP_LAUNCH = "BINGE-APP-LAUNCH"   //done

/*Login Screen Events*/
const val EVENT_LOGIN_OTP_RECEIVED = "LOGIN-OTP-RECEIVED"   //done
const val EVENT_LOGIN_SCREEN_VISIT = "LOGIN-ENTER"
const val EVENT_LOGIN_OTP_ENTER = "LOGIN-OTP-ENTER" //done
const val EVENT_LOGIN_GET_OTP = "LOGIN-GET-OTP" //done
const val EVENT_LOGIN_OTP_RESEND = "LOGIN-OTP-RESEND"   //done
const val EVENT_LOGIN_OTP_INVOKE = "LOGIN-OTP-INVOKE"
const val EVENT_LOGIN_PASSWORD = "LOGIN-PASSWORD"   //done
const val EVENT_LOGIN_SUCCESS = "LOGIN-SUCCESS" //done
const val EVENT_LOGIN_FAILED = "LOGIN-FAILURE"   //done
const val EVENT_LOGOUT = "LOGOUT"   //done
const val EVENT_MOE_LOGOUT = "MOE-LOGOUT"
const val EVENT_LOGOUT_FAILED = "LOGOUT-FAILED" //done
const val EVENT_NON_TS_RMN = "NON-TS-RMN"   //done
const val EVENT_NOT_A_TS_USER_CLICK = "NOT-A-TS-USER-BUTTON-CLICK"  //done
const val EVENT_FORGOT_PASSWORD = "FORGOT-PASSWORD" //done
const val EVENT_PASSWORD_RESET_SUCCESS = "PASSWORD-RESET-SUCCESS"   //done
const val EVENT_PASSWORD_RESET_FAILED = "PASSWORD-RESET-FAILED" //done
const val EVENT_UPDATE_PASSWORD_INVOKED = "UPDATE-PASSWORD-INVOKED" //done
const val EVENT_UPDATE_PASSWORD_SUCCESS = "UPDATE-PASSWORD-SUCCESS" //done
const val EVENT_UPDATE_PASSWORD_FAILED= "UPDATE-PASSWORD-FAILED"    //done
const val EVENT_LOGIN_PAGE_VISIT = "LOGIN-PAGE-VISIT"   //done
const val EVENT_LOGIN_PAGE_NEWLOGIN = "LOGIN-PAGE-NEWLOGIN" //done
const val EVENT_LOGIN_PAGE_NOTNOW = "LOGIN-PAGE-NOTNOW" //done
const val EVENT_LOGIN_RMN_ENTER_INVALID = "LOGIN-RMN-ENTER-INVALID" //done
const val EVENT_LOGIN_RMN_ENTER = "LOGIN-RMN-ENTER" //done
const val EVENT_LOGIN_LIC_AGREEMENT = "LOGIN-LIC-AGREEMENT" //done
const val EVENT_LOGIN_LIC_AGREEMENT_BACK = "LOGIN-LIC-AGREEMENT-BACK" //done
const val EVENT_LOGIN_SKIP = "LOGIN-SKIP"   //done
const val EVENT_LOGIN_SUBSCRIPTIONID_SELECT = "LOGIN-SUBSCRIPTIONID-SELECT" //need to track
const val EVENT_LOGIN_MY_PLAN_STARTWATCHING = "LOGIN-MY-PLAN-STARTWATCHING" //need to track
const val EVENT_PARENTAL_CONTROL_CLICK = "PARENTAL-CONTROL-CLICK"   //done
const val EVENT_SET_RESTRICTION_INITIATE = "SET-RESTRICTION-INITIATE"   //done
const val EVENT_SET_RESTRICTION_PROCEED = "SET-RESTRICTION-PROCEED"     //done
const val EVENT_PARENTAL_PIN_OTP_INITIATE = "PARENTAL-PIN-OTP-INITIATE"     //done
const val EVENT_PARENTAL_PIN_OTP_PROCEED = "PARENTAL-PIN-OTP-PROCEED"   //done
const val EVENT_CREATE_PIN_INITIATE = "CREATE-PIN-INITIATE"     //done
const val EVENT_CREATE_PIN_PROCEED = "CREATE-PIN-PROCEED"   //done
const val EVENT_CREATE_PIN_CANCEL = "CREATE-PIN-CANCEL"   //done
const val EVENT_PIN_ENTRY_INITIATE = "PIN-ENTRY-INITIATE"   //done
const val EVENT_PIN_ENTRY_PROCEED = "PIN-ENTRY-PROCEED"   //done
const val EVENT_PIN_ENTRY_FORGOT = "PIN-ENTRY-FORGOT"   //done
const val EVENT_PIN_ENTRY_NOT_NOW = "PIN-ENTRY-NOT-NOW"   //done
const val EVENT_PIN_ENTRY_INCORRECT = "PIN-ENTRY-INCORRECT"   //done
const val EVENT_CONTENT_CLICK = "CONTENT-CLICK"     //done
const val EVENT_CONTENT_PLAY_END = "CONTENT-PLAY-END"   //done
const val EVENT_APPS_RAIL_CLICK = "APPS-RAIL-CLICK"     //Done
const val EVENT_BROWSE_BY_LANGUAGE_RAIL_CLICK = "BROWSE-BY-LANGUAGE-RAIL-CLICK"     //Done
const val EVENT_BROWSE_BY_GENRE_RAIL_CLICK = "BROWSE-BY-GENRE-RAIL-CLICK"   //Done
const val EVENT_SHARE_CLICK = "SHARE-CLICK"     //done
const val EVENT_CONTENT_PLAY = "CONTENT-PLAY"   //done
const val EVENT_CONTENT_PLAY_FAIL = "CONTENT-PLAY-FAIL" //done
const val EVENT_WHATSAPP_SHARE_CLICK = "WHATSAPP-SHARE-CLICK"  //done
const val PLAY = "PLAY"
const val CHANGE_RESTRICTION = "CHANGE RESTRICTION"
const val LOGIN_OTP_REQUESTED = "LOGIN-OTP-REQUESTED"

// Apple Tv Events
const val EVENT_ACTIVATE_APPLE_TV_SUBSCRIPTION_CLICK="ACTIVATE-APPLE-TV-SUBSCRIPTION-CLICK"
const val EVENT_APPLE_PLAY_CTA_CLICK="APPLE-PLAY-CTA-CLICK"
const val EVENT_APPLE_ACTIVATE_NOW_CLICK="APPLE-ACTIVATE-NOW-CLICK"
const val EVENT_LINK_APPLE_TV_ACCOUNT_CLICK="LINK-APPLE-TV-ACCOUNT-CLICK"

/*Subscription Screen events*/
const val EVENT_MODIFY_INITIATE = "MODIFY-PACK-INITIATE"
const val EVENT_MODIFY_SUCCESS = "MODIFY-PACK-SUCCESS"
const val EVENT_PACK_SELECTED = "PACK-SELECTED"
const val EVENT_SUBSCRIPTION_CANCEL = "PACK-CANCELLATION"
const val EVENT_SUBSCRIPTION_REVOKE = "CANCELLATION-REVOKED"
const val EVENT_SUBSCRIPTION_CANCEL_SKIP = "PACK-CANCEL-SKIP"
const val EVENT_SUBSCRIPTION_REVOKE_SKIP = "PACK-REVOKE-SKIP"
const val EVENT_FREE_TRIAL_LATER = "FREE-TRIAL-LATER"
const val EVENT_NUDGE_CLICk = "NUDGE-CLICK"

const val EVENT_MY_PLAN_VIEW = "MY-PLAN-VIEW" //done
const val EVENT_MY_PLAN_CHANGE_PLAN = "MY-PLAN-CHANGE-PLAN"//done
const val EVENT_MY_PLAN_CHANGE_TENURE = "MY-PLAN-CHANGE-TENURE"//done
const val EVENT_MY_PLAN_RENEW = "MY-PLAN-RENEW-PLAN"//done
const val EVENT_MY_PLAN_RENEW_OTHER_OPTIONS = "MY-PLAN-RENEW-OTHER-OPTIONS"//done

const val EVENT_MY_PLAN_RENEW_CHANGE_TENURE = "MY-PLAN-RENEW-CHANGE-TENURE"//done
const val EVENT_MY_PLAN_RENEW_CHANGE_PLAN = "MY-PLAN-RENEW-CHANGE-PLAN"//done
const val EVENT_MY_PlAN_CANCEL_PLAN = "MY-PLAN-CANCEL-PLAN"//done
const val EVENT_MY_PLAN_CANCEL_PLAN_PROCEED = "MY-PLAN-CANCEL-PLAN-PROCEED"//done
const val EVENT_MY_PLAN_CANCEL_PLAN_LATER = "MY-PLAN-CANCEL-PLAN-LATER"//done

const val EVENT_MY_PLAN_DONT_CANCEL_PLAN = "MY-PLAN-DONT-CANCEL-PLAN" //done
const val EVENT_MY_PLAN_CANCEL_PRIME = "MY-PLAN-CANCEL-PRIME"//done
const val EVENT_MY_PLAN_CANCEL_PRIME_CONFIRM = "MY-PLAN-CANCEL-PRIME-CONFIRM"//done

const val EVENT_SUBSCRIBE_SUCCESS = "SUBSCRIBE-SUCCESS"
const val EVENT_SUBSCRIBE_FAILED = "SUBSCRIBE-FAILED"
const val EVENT_MODIFY_PACK_SUCCESS = "MODIFY-PACK-SUCCESS"
const val EVENT_PACK_SELECTION_INITIATE = "PACK-SELECTION-INITIATE"

const val EVENT_PACK_SELECTION_VIEWS = "PACK-SELECTION-VIEWS"
const val EVENT_PACK_COMPARE_PLANS_VIEW = "PACK-COMPARE-PLANS-VIEW"
const val EVENT_PACK_COMPARE_PLANS_SELECTION = "PACK-COMPARE-PLANS-SELECTION"
const val EVENT_PACK_TENURE_VIEW = "PACK-TENURE-VIEW"
const val EVENT_ADD_PACK_SKIP = "ADD-PACK-SKIP"
const val EVENT_ADD_PACK_CONTINUE = "ADD-PACK-CONTINUE"
const val EVENT_PAYMENT_SUCCESS_POPUP_STARTWATCHING = "PAYMENT-SUCCESS-POPUP-STARTWATCHING"

const val EVENT_SUBSCRIPTION_DRAWER_INITIATE = "SUBSCRIPTION-DRAWER-INITIATE"
const val EVENT_SUBSCRIPTION_DRAWER_DO_IT_LATER = "SUBSCRIPTION-DRAWER-DO-IT-LATER"
const val EVENT_SUBSCRIPTION_DRAWER_PROCEED = "SUBSCRIPTION-DRAWER-PROCEED"
const val EVENT_SUBSCRIPTION_DRAWER_EXISTING_USER_LOGIN = "SUBSCRIPTION-DRAWER-EXISTING-USER-LOGIN"
const val EVENT_SUBSCRIPTION_DRAWER_CLOSE = "SUBSCRIPTION-DRAWER-CLOSE"

const val EVENT_SUBSCRIPTION_PAGE_PROCEED = "SUBSCRIPTION-PAGE-PROCEED"
const val EVENT_SUBSCRIPTION_PAGE_INITIATE = "SUBSCRIPTION-PAGE-INITIATE"
const val EVENT_PAYMENT_FLOW_EXIT = "PAYMENT-FLOW-EXIT"


const val SUB_DRAWER_LAUNCH_MYOP = "SUBSCRIPTION-DRAWER-INITIATE"
const val SUB_DRAWER_SELECT_MYOP = "SUBSCRIPTION-DRAWER-MYOP-SELECT"
const val SUB_DRAWER_CURATED_SELECT_MYOP = "SUBSCRIPTION-DRAWER-CURATED-SELECT"
const val SUB_DRAWER_CURATED_EXPLORE = "SUBSCRIPTION-DRAWER-EXPLORE"
const val SUB_DRAWER_DO_IT_LATER_MYOP = "SUBSCRIPTION-DRAWER-DO-IT-LATER"
const val SUB_DRAWER_CLOSE_MYOP = "SUBSCRIPTION-DRAWER-CLOSE "
const val APP_LAUNCH = "APP-LAUNCH"
const val CONTENT_PLAYBACK = "CONTENT-PLAYBACK"
const val HOME_SUBSCRIBE_CTA = "HOME-SUBSCRIBE-CTA"
const val HAMBURGER_SUBSCRIBE_CTA = "HAMBURGER-SUBSCRIBE-CTA"

/*Device List Management Events*/
const val EVENT_LIST_DEVICES = "LIST-DEVICES"   //done
const val EVENT_REMOVE_DEVICES = "REMOVE-DEVICE"
const val EVENT_MAX_DEVICE = "MAX-DEVICE-LIMIT" //done

/*Content Language Events*/
const val EVENT_CONTENT_LANG_SELECT = "CONTENT-LANG-SELECT" //Done
const val EVENT_CONTENT_LANG_EXPAND = "CONTENT-LANG-EXPAND" //Done
const val EVENT_CONTENT_LANG_SKIP = "CONTENT-LANG-SKIP" //Done
const val PARA_LANGUAGE1 = "LANGUAGE1"
const val PARA_LANGUAGE2 = "LANGUAGE2"
const val PARA_LANGUAGE3 = "LANGUAGE3"
const val PARA_LANGUAGE4 = "LANGUAGE4"
const val EVENT_CONTENT_LANG_OPEN = "CONTENT-LANG-OPEN"
const val EVENT_CONTENT_LANG_PROCEED = "CONTENT-LANG-PROCEED"

/*Device List Management Parameters/values*/
const val PARA_DEVICE = "DEVICE"
const val PARA_DEVICE_METHOD = "DEVICE-METHOD"
const val MOBILE = "MOBILE"
const val PARA_DEVICE_LIST = "DEVICE-LIST"
const val EVENT_DEVICE_LIMIT_POPUP = "DEVICE-LIMIT-POPUP" //done
const val EVENT_DEVICE_LIMIT_REVIEW = "DEVICE-LIMIT-REVIEW" //done
const val EVENT_DEVICE_LIMIT_SKIP = "DEVICE-LIMIT-SKIP" //done
const val EVENT_DEVICE_LISTING_VIEW = "DEVICE-LISTING-VIEW" //done
const val EVENT_DEVICE_LISTING_REMOVE = "DEVICE-LISTING-REMOVE" //done
const val EVENT_DEVICE_LISTING_EXIT = "DEVICE-LISTING-EXIT" //done
const val EVENT_DEVICE_REMOVE_CONFIRMATION_POPUP = "DEVICE-REMOVE-CONFIRMATION-POPUP"   //done
const val EVENT_DEVICE_REMOVE_SKIP = "DEVICE-REMOVE-SKIP"   //done
const val EVENT_DEVICE_REMOVE_ERROR = "DEVICE-REMOVE-ERROR" //done
const val EVENT_DEVICE_REMOVE_CONFIRM = "DEVICE-REMOVE-CONFIRM" //done

/*Search Events*/
const val EVENT_SEARCH_START = "SEARCH-START"
const val EVENT_SEARCH_INITIATE = "SEARCH-INITIATE"  //Done
const val EVENT_SEARCH = "SEARCH"
const val EVENT_NO_SEARCH_RESULT = "NO-SEARCH-RESULT"
const val EVENT_SEARCH_RESULT = "SEARCH-RESULT"
const val EVENT_SEARCH_MIC = "SEARCH-MIC"
const val EVENT_SEARCH_VOICE_PERMISSION = "SEARCH-VOICE-PERMISSION" //done
const val EVENT_SEARCH_REACTIVATE_MIC = "SEARCH-REACTIVATE-MIC"     //done
const val EVENT_SEARCH_HOME_CLICKS = "SEARCH-HOME-CLICKS"   //need to track
const val EVENT_SEARCH_RESULT_CLICKS = "SEARCH-RESULT-CLICKS"   //done
const val EVENT_SEARCH_HOME = "SEARCH-HOME"     //Done
const val EVENT_SEARCH_RESULT_SWIPE = "SEARCH-RESULT-SWIPE" //Done

/*Search Suggestion Events*/
const val EVENT_AUTO_SUGGESTION_INITIATE = "AUTO-SUGGESTION-INITIATE"
const val EVENT_AUTO_SUGGESTION_SCROLLED = "AUTO-SUGGESTION-SCROLLED"
const val EVENT_AUTO_SUGGESTION_CLICKED = "AUTO-SUGGESTION-CLICKED"

const val PARA_SCROLL_DIRECTION = "SCROLL-DIRECTION"
const val PARA_KEYBOARD_STATE = "KEYBOARD-STATE"


/*Home & PI Events*/
const val EVENT_HOME_SCREEN_VISIT = "HOME-PAGE-VIEW"
const val EVENT_RAIL_WATCHED = "VIEW-RAIL-CONTENT"
const val EVENT_BANNER_VIEW = "VIEW-HERO-BANNER"
const val EVENT_HOME_CLICK = "HOME-CLICK"
const val EVENT_SEE_ALL = "SEE-ALL"
const val EVENT_DETAIL_SCREEN_VISIT = "VIEW-CONTENT-DETAIL"
const val EVENT_PLAY_TRAILER = "PLAY-TRAILER"
const val EVENT_SHARE_WHATSAPP = "SHARE-WHATSAPP"
const val EVENT_SHARE = "SHARE"
const val EVENT_SHUFFLE_CLICK = "SHUFFLE-CLICK" //Done
const val EVENT_PAGE_CLICK = "PAGE-CLICK"   //Done
const val EVENT_ADD_WATCHLIST = "ADD-WATCHLIST" //Done
const val EVENT_REMOVE_WATCHLIST = "REMOVE-WATCHLIST"//Done

/*Player Screen Events*/
const val EVENT_PLAY_CONTENT = "PLAY-CONTENT"
const val EVENT_INITIAL_BUFFER_TIME = "INITIAL-BUFFER-TIME"
const val EVENT_PAUSE_CONTENT = "PAUSE-CONTENT"
const val EVENT_RESUME_CONTENT = "RESUME-CONTENT"
const val EVENT_PLAYBACK_FAILURE = "PLAYBACK-FAILURE"

/*Watchlist Events*/
const val EVENT_VIEW_WATCHLIST = "VIEW-WATCHLIST"
const val EVENT_SCREEN_VIEW_BINGELIST = "BINGELIST"
const val EVENT_ADD_FAVORITE = "ADD-CONTENT-FAVOURITE"
const val EVENT_DELETE_FAVORITE = "DELETE-FAVORITE"

/*Recharge/Payment related event/param*/
const val EVENT_RECHARGE_INITIATE = "RECHARGE-INITIATE" //done
const val EVENT_TP_RECHARGE_INITIATE = "TP-RECHARGE-INITIATE" //done
const val EVENT_RECHARGE_FAILED = "RECHARGE-FAILED" //done
const val EVENT_TP_RECHARGE_FAILED = "TP-RECHARGE-FAILED" //done
const val EVENT_RECHARGE = "RECHARGE"
const val EVENT_TP_RECHARGE_SUCCESS = "TP-RECHARGE-SUCCESS"
const val PARAM_RENEWAL_MODE = "RENEWAL-MODE"
const val PARAM_SUBSCRIBER_BALANCE = "SUBSCRIBER-BALANCE"
const val PARAM_TRANSACTION_STATUS = "TRANSACTION-STATUS"
const val PARAM_CARD_TYPE = "CARD-TYPE"
const val PARAM_BANK_NAME = "BANK-NAME"
const val PARAM_WALLET_NAME = "WALLET-NAME"
const val PARAM_TRANSACTION_ID = "TRANSACTION-ID"
const val PARAM_CARD_NAME = "CARD-NAME"
const val PARAM_FAILURE_REASON = "FAILURE-REASON"
const val PARA_EXIT_STATUS = "EXIT-STATUS"
const val PARA_PAYMENT_STATUS = "PAYMENT-STATUS"
const val PARA_PG_RESPONSE_CODE = "PG-RESPONSE-CODE"

/*FTV WO events*/
const val EVENT_FTV_UPSELL_VIEW = "FTV-UPSELL-VIEW"
const val EVENT_FTV_UPSELL_CONVERTED = "FTV-UPSELL-CONVERTED"
const val EVENT_FTV_WO = "FTV-WO"

/*Generic Events*/
const val EVENT_TERMS_CONDITION_VISIT = "TERMS-CONDITIONS"
const val EVENT_PRIVACY_POLICY_VISIT = "PRIVACY-POLICY"
const val EVENT_CONTACT_US_VISIT = "CONTACT-US"
const val EVENT_NOTIFICATION_SETTING = "NOTIFICATION-SETTINGS"
const val EVENT_EDIT_PROFILE_VISIT = "EDIT-PROFILE"     //done
const val EVENT_ADD_PROFILE = "ADD-PROFILE" //need to track
const val EVENT_TRANSACTION_HISTORY_VISIT = "TRANSACTION-HISTORY"
const val EVENT_AUTO_PLAY_SETTING = "AUTOPLAY-TRAILER-SETTING"
const val EVENT_UPDATE_PROFILE = "UPDATE-PROFILE"
const val EVENT_FAQ_VIEW= "FAQ-VIEW"
const val EVENT_ACCOUNT_SCREEN_VISIT = "HOME-ACCOUNT"
const val EVENT_SWITCH_PROFILE = "SWITCH-PROFILE"   //done
const val EVENT_SET_DEFAULT_PROFILE = "SET-DEFAULT-PROFILE"   //need to track
const val EVENT_VIEW_NOTIFICATION= "VIEW-NOTIFICATION"

/*Amazon Prime Events*/
const val EVENT_PRIME_ADD = "PRIME-ADD-PACK"    //done
const val EVENT_PRIME_ADD_CONTINUE = "PRIME-ADD-PACK-CONTINUE"  //done
const val EVENT_PRIME_ADD_SKIP = "PRIME-PACK-SKIP"
const val EVENT_PRIME_LOW_BALANCE = "PRIME-LOW-BALANCE"     //done
const val EVENT_PRIME_LOW_BALANCE_SKIP = "PRIME-LOW-BALANCE-SIGN-UP-CANCEL"
const val EVENT_PRIME_SUSPEND = "PRIME-SUSPEND-ALERT"       //done
const val EVENT_PRIME_RESUME_SUCCESS = "PRIME-RESUME-SUCCESS"   //done
const val EVENT_PRIME_UPSELL = "PRIME-UPSELL"
const val EVENT_PRIME_CONTENT_CLICK = "PRIME-CONTENT-CLICK" //done

const val EVENT_ERROR = "ERROR"

/*Firebase Facebook Events*/
const val EVENT_START_TRIAL = "StartTrial"
const val EVENT_PURCHASE = "Purchase"
const val EVENT_COMPLETE_REGISTRATION = "CompleteRegistration"
const val EVENT_SUBSCRIBE = "SUBSCRIBE"
const val EVENT_SUBSCRIBED = "Subscribed"
const val EVENT_UNSUBSCRIBED = "Unsubscribed"

/*Appsflyer events and params*/
const val EVENT_PLAY_CONTENT_PREMIUM = "PLAY-CONTENT-PREMIUM"
const val EVENT_PLAY_CONTENT_TVOD = "PLAY-CONTENT-TVOD"
const val EVENT_PLAY_CONTENT_FREEMIUM = "PLAY-CONTENT-FREEMIUM"
const val EVENT_RECHARGE_SUCCESS = "RECHARGE-SUCCESS"
const val EVENT_VIEW_LOGIN = "VIEW-LOGIN"
const val EVENT_VIEW_LANGUAGE = "VIEW-LANGUAGE"
const val EVENT_VIEW_GENRE = "VIEW-GENRE"
const val EVENT_VIEW_PACK_LISTING = "VIEW-PACKLISTING"
const val EVENT_VIEW_FREE_TRIAL = "VIEW-FREEPACK" // To track free trial screen view
const val EVENT_VIEW_MY_SUBSCRIPTION = "VIEW-MYSUBSCRIPTION"
const val EVENT_VIEW_RECHARGE = "VIEW-RECHARGE"
const val EVENT_SUBSCRIPTION_SUCCESS = "SUBSCRIPTION-SUCCESS"
const val EVENT_FREE_TRIAL_SUCCESS = "FREE-TRIAL-SUCCESS"
const val PACK_TYPE_FREE = "FREE"
const val PACK_TYPE_PAID = "PAID"
const val SOURCE_DEEPLINK = "Deeplink"
const val SOURCE_CHATBOT_DEEPLINK = "CHATBOT-DEEPLINK"
const val EVENT_MY_PLAN = "MY-PLAN"
const val EVENT_PARENTAL_CONTROL = "PARENTAL-CONTROL"
const val SOURCE_NUDGES = "Nudges"
const val SOURCE_RENEWAL_NUDE = "RENEWAL_NUDGE"
const val SOURCE_MIDSCROLL_NUDGE = "MIDROLL_NUDGE"
const val SOURCE_GAME_NUDGE = "GAME_NUDGE"
const val SOURCE_SUBSCRIBE_NUDGE = "SUBSCRIBE_NUDGE"
const val SOURCE_FREETRIAL_NUDEGE = "FREETRIAL_NUDGE"
const val EVENT_PAYMENT = "PAYMENT"
const val EVENT_SIGN_UP = "SIGN-UP"
const val PACK_ID = "PACK-ID"
const val PACK_DURATION = "PACK-DURATION"
const val CURRENCY_INR = "INR"
const val PROMO_CODE = "PROMO-CODE"
const val PAYMENT_MODE = "PAYMENT-MODE"
const val EVENT_SUBSCRIBE_SUCCESS_NEW = "SUBSCRIBE-SUCCESS-NEW"
const val EVENT_SUBSCRIBE_SUCCESS_REPEAT = "SUBSCRIBE-SUCCESS-REPEAT"
const val EVENT_SUBSCRIBE_SUCCESS_MODIFY_PACK = "SUBSCRIBE-SUCCESS-MODIFY-PACK"
const val OLD_PACK_ID = "OLD-PACK-ID"
const val COMVIVA_ID = "ComvivaID"
const val MOBILE_NUMBER = "Mobile-Number"
const val USER_LOGIN_STATE = "USER-LOGIN-STATE"
const val LOGIN_STATE_NON_LOGGED_IN = "Non-Logged-In"
const val LOGIN_STATE_LOGGED_IN = "Logged-In"
const val LISTING_TYPE = "LISTING-TYPE"
const val LISTING_TYPE_LANDING_PAGE = "Landing Page"
const val LISTING_TYPE_DRAWER = "Drawer"
const val EVENT_VIEW_PAYMENT = "VIEW-PAYMENT"
const val EVENT_PLAY_CONTENT_PREMIUM_VTR75 = "PLAY-CONTENT-PREMIUM-VTR75"
const val EVENT_PLAY_CONTENT_PREMIUM_VTR50 = "PLAY-CONTENT-PREMIUM-VTR50"

const val EVENT_FIRST_USER_INVENTION = "FIRST-USER-INVENTION"
const val EVENT_FIRST_CONTENT_CLICK = "FIRST-CONTENT-CLICK"
const val EVENT_FIRST_CONTENT_FREE_PLAY = "FIRST-CONTENT-FREE-PLAY"
const val EVENT_FIRST_CONTENT_PREMIUM_PLAY = "FIRST-CONTENT-PREMIUM-PLAY"
const val EVENT_FILTER_TOGGLE = "FILTER-TOGGLE"


/*Login Screen Events Parameters*/
const val PARA_SOURCE = "SOURCE"
const val PARA_TYPE = "TYPE"
const val PARA_VALUE = "VALUE"
const val PARA_AUTH = "AUTH"
const val PARA_REASON = "REASON"
const val PARA_DTH_STATUS = "DTH-STATUS"
const val PARA_COUNTER_VALUE = "COUNTER-VALUE"
const val PARA_DISPLAYED_ON_DAY = "DISPLAYED-ON-DAY"
const val PARA_FREE_TRIAL_AVAILED = "FREE-TRIAL-AVAILED"
const val PARA_NUDGE_TYPE = "NUDGE-TYPE"
const val PARA_FDO_REGISTERED = "FDO-REGISTERED"
const val PARA_FDO_DAY = "FDR-RAISED-ON-DAY"
const val PARA_SID = "SID"
const val PARA_TO_BAID = "TO-BAID"
const val PARA_WITH_PASSWORD = "WITH-PASSWORD"
const val PARA_RESTRICTION = "RESTRICTION"

/*DRP Screen Events VALUES*/
const val PARA_DRP_ENABLE = "DRP-ENABLE"


/*Login Screen Events VALUES*/
const val BINGE_MOBILE = "Binge-Mobile"
const val SOURCE_APP_LAUNCH = "App Launch"
const val SOURCE_SWITCH_SUBSCRIPTION = "Switch Subscription"
const val SOURCE_DEVICE_MGMT = "Device Management"
const val SOURCE_MARKETING = "Marketing Screen"
const val SOURCE_LOGOUT = "LOGOUT"
const val SOURCE_MORE = "More"
const val SOURCE_LOGIN = "Login"
const val SOURCE_SUBSCRIPTION = "Subscription"
const val SOURCE_MIX = "MIX"
const val SOURCE_NOTIFICATION = "NOTIFICATION"
const val SOURCE_NOTIFICATION_ERROR = "NOTIFICATION_ERROR"
const val SOURCE_PARTNER_HOME = "Partner Home"
const val SOURCE_CONTENT = "Content"
const val SOURCE_PLAY_CLICK = "PLAYBACK"
const val SOURCE_HOME = "Home"
const val SOURCE_MANAGED_APPS = "Managed Apps"
const val SOURCE_HAMBURGER = "HAMBURGERMENU"
const val SOURCE_MOVIES = "Movies"
const val SOURCE_TV_SHOWS = "Shows"
const val SOURCE_KIDS = "Kids"
const val SOURCE_SPORTS = "Sports"
const val SOURCE_GAMES = "Games"
const val SOURCE_WATCHLIST = "Watchlist"
const val SOURCE_SEARCH = "Search"
const val SOURCE_SEE_ALL = "See All"
const val SOURCE_SWITCH_ACCOUNT= "Switch-Account"
const val SOURCE_PASSWORD = "PASSWORD"
const val SOURCE_Password = "Password"
const val SOURCE_OTP = "OTP"
const val SOURCE_BINGE_LIST = "BINGE_LIST"

const val SOURCE_ACCOUNT = "My Account"
const val SOURCE_CATEGORY = "Category"

/* Misc Events */
const val EVENT_MIDSCROLL_CLICK="MIDSCROLL-CLICK"
const val EVENT_RENEWAL_NUDGE_CLICK="RENEWAL-NUDGE-CLICK"
const val EVENT_SUBSCRIBE_FREETRIAL_NUDGE_CLICK="SUBSCRIBE-FREETRIAL-NUDGE-CLICK"
const val EVENT_SUBSCRIBE_FREEMIUM_NUDGE_CLICK="SUBSCRIBE-FREEMIUM_NUDGE-CLICK"
const val EVENT_NOTIFICATION_NUDGE_CLICK="NOTIFICATION-NUDGE-CLICK"
const val EVENT_EMAIL_NUDGE_CLICK="EMAIL_NUDGE-CLICK"
const val EVENT_START_FREE_TRIAL="START-FREE-TRIAL"
const val EVENT_SUBSCRIBE_POPUP="SUBSCRIBE-POPUP"
const val EVENT_SUBSCRIBE_POPUP_SUBSCRIBE="SUBSCRIBE-POPUP-SUBSCRIBE"
const val EVENT_SUBSCRIBE_POPUP_CANCEL="SUBSCRIBE-POPUP-CANCEL"
const val EVENT_UPGRADE_POPUP="UPGRADE-POPUP"
const val EVENT_UPGRADE_POPUP_UPGRADE="UPGRADE-POPUP-UPGRADE"
const val EVENT_UPGRADE_POPUP_CANCEL="UPGRADE-POPUP-CANCEL"
const val EVENT_TRAILER_AUTOPLAY="TRAILER-AUTOPLAY"
const val EVENT_HORIZONTAL_SWIPE="HORIZONTAL-SWIPE"
const val EVENT_SYNOPSIS_MORE_CLICK="SYNOPSIS-MORE-CLICK"
const val EVENT_SEE_ALL_EPISODES="SEE-ALL-EPISODES"
const val EVENT_HOME_PAGE_VIEW="HOME-PAGE-VIEW"
const val EVENT_MENU_CLICK="MENU-CLICK"
const val EVENT_MENU_OPTION="MENU-OPTION"
const val EVENT_SETTINGS_VISITS="SETTINGS-VISITS"
const val EVENT_SETTINGS_MENU_OPTION="SETTINGS-MENU-OPTION"
const val EVENT_HERO_BANNER_CLICKS="HERO-BANNER-CLICKS"
const val EVENT_GAMES_VIEW_HERO_BANNER="GAMES-VIEW-HERO-BANNER"
const val APP_RATING_POP_UP_INITIATE="APP-RATING-POP-UP-INITIATE"
const val APP_RATING_POP_UP_YES="APP-RATING-POP-UP-YES"
const val APP_RATING_POP_UP_NOT_REALLY="APP-RATING-POP-UP-NOT-REALLY"

/*Values*/
const val SELF = "SELF"
const val Force = "Force"
const val Cancelled = "Cancelled"
const val Failed = "Failed"

const val EVENT_WATCHLIST_SCREEN_VISIT = "HOME-WATCHLIST"
const val EVENT_DELETE_NOTIFICATION= "DELETE-NOTIFICATION"

const val EVENT_EMAIL_US = "EMAIL-US"
const val EVENT_RAISE_REQUEST = "RAISE-REQUEST"
const val EVENT_CALL_TATASKY = "CALL-TATASKY"
const val EVENT_CHAT_WITH_TATASKY = "CHAT-WITH-TATASKY"


const val EVENT_RESTART_CLICK = "RESTART-CLICK"
const val EVENT_THIRD_PARTY_PLAYER_LAUNCH = "THIRD-PARTY-PLAYER-LAUNCH"

/*Home PARAMETERS*/
const val PARA_TYPE_SECTION = "TYPE-SECTION"
const val PARA_SECTION = "SECTION"
const val PARA_HERO_BANNER_NUMBER = "HERO-BANNER-NUMBER"
const val PARA_CONFIG_TYPE = "CONFIG-TYPE"
const val PARA_CARD_CONFIG_TYPE = "CARD-CONFIG-TYPE"
const val PARA_CONTENT_TYPE = "CONTENT-TYPE"
const val PARA_CONTENT_LANGUAGE = "CONTENT-LANGUAGE"
const val PARA_CONTENT_LANGUAGE_PRIMARY = "CONTENT-LANGUAGE-PRIMARY"
const val PARA_CONTENT_GENRE = "CONTENT-GENRE"
const val PARA_CONTENT_GENRE_PRIMARY = "CONTENT-GENRE-PRIMARY"
const val PARA_CONTENT_PARTNER = "CONTENT-PARTNER"
const val PARA_CONTENT_PARTNER_SELECTED = "CONTENT-PARTNER_SELECTED"
const val PARA_CONTENT_AUTH = "CONTENT-AUTH"
const val PARA_CONTENT_CATEGORY = "CONTENT-CATEGORY"
const val PARA_CONTENT_RATING = "CONTENT-RATING"
const val PARA_RELEASE_YEAR = "RELEASE-YEAR"
const val PARA_DEVICE_TYPE = "DEVICE-TYPE"
const val PARA_ACTORS = "ACTORS"
const val PARA_PARENT_CONTENT_TITLE = "PARENT-CONTENT-TITLE"
const val PARA_LIVE_CONTENT = "LIVE-CONTENT"
const val PARA_FREE_CONTENT = "FREE-CONTENT"
const val PARA_PAGE_NAME = "PAGE-NAME"
const val PARA_PARTNER = "PARTNER"
const val PARA_PARTNER_NAME = "PARTNER-NAME"
const val PARA_CONTENT_TITLE = "CONTENT-TITLE"
const val PARA_TITLE_RAIL = "RAIL-TITLE"
const val PARA_RAIL_TYPE = "RAIL-TYPE"
const val PARA_GENRE = "CONTENT-GENRE"
const val PARA_LANGUAGE = "CONTENT-LANGUAGE"
const val PARA_RAIL_POSITION = "RAIL-POSITION"
const val PARA_CONTENT_POSITION = "CONTENT-POSITION"
const val PARA_PARTNER_HOME = "PARTNER-HOME"
const val PARA_RAIL = "RAIL"
const val PARA_Rail = "Rail"
const val PARA_RAIL_CATEGORY = "RAIL-CATEGORY"
const val PARA_ORIGIN = "ORIGIN"
const val PARA_AMOUNT = "AMOUNT"
const val PARA_PACK_AMOUNT = "PACK-AMOUNT"
const val PARA_ENABLED = "ENABLED"
const val PARA_DISABLED = "DISABLED"
const val PARA_ALLOWED = "ALLOWED"
const val PARA_WATCH_NOTIFICATION = "WATCH-NOTIFICATIONS"
const val PARA_TRANSACTION_NOTIFICATION = "TRANSACTION-NOTIFICATIONS"
const val PARA_VIEW_TYPE = "VIEW-TYPE"
const val PARA_IS_FROM_NUDGE = "IS-FROM-NUDGE"
const val PARA_BUFFER_DURATION_MINUTES = "BUFFER-DURATION-MINUTES"
const val PARA_BUFFER_DURATION_SECONDS = "BUFFER-DURATION-SECONDS"
const val PARA_NUMBER_OF_PAUSE = "NUMBER-OF-PAUSE"
const val PARA_NUMBER_OF_RESUME = "NUMBER-OF-RESUME"
const val PARA_SEEK_BAR_PROGRESS = "SEEK-BAR-PROGRESS"
const val PARA_VIDEO_QUALITY = "VIDEO-QUALITY"
const val PARA_WATCH_DURATION_SECONDS = "WATCH-DURATION-SECONDS"
const val PARA_WATCH_DURATION_MINUTES = "WATCH-DURATION-MINUTES"
const val PARA_CONTENT_PARTNER_POSITION = "CONTENT-PARTNER-POSITION"
const val PARA_FILTER_SELECTED = "FILTER-SELECTED"
const val PARA_SEARCH = "SEARCH"
const val LANGUAGE_SELECTED = "LANGUAGE-SELECTED"
const val GENRE_SELECTED = "GENRE-SELECTED"
const val RAIL_LANGUAGE_POSITION = "RAIL-LANGUAGE-POSITION"
const val RAIL_GENRE_POSITION = "RAIL-GENRE-POSITION"
const val PAGE_RESULT_SWIPE = "PAGE-RESULT-SWIPE"
const val PARA_ZEE5_TAG = "Zee5Tag"
const val PARA_APPLE_COUPON_STATUS = "APPLE-COUPON-STATUS"


/*Home Values*/
const val HERO = "HERO"
const val BANNER = "BANNER"
const val RAIL = "Rail"
const val APPS = "Apps"
const val HERO_BANNER_NUMBER = "Hero-Banner-number"
const val EDITORIAL = "EDITORIAL"
const val RECOMMENDATION = "Recommendation"
const val HB_SEE_ALL_VALUE = "HB SEE ALL"
const val MOVIES = "MOVIES"
const val TV_SHOWS = "TV_SHOWS"
const val WEB_SHORTS = "WEB_SHORTS"
const val IVOD = "IVOD"
const val IVOD_CATEGORY = "IVOD_CATEGORY"
const val IVOD_SUB_CATEGORY = "IVOD_SUB_CATEGORY"
const val BRAND = "BRAND"
const val SERIES = "SERIES"

/*Search Parameters*/
const val PARA_KEYWORD = "KEYWORD"
const val PARA_SEARCH_KEYWORD = "SEARCH-KEYWORD"
const val PARA_SCREEN_NAME = "SCREEN-NAME"
const val PARA_SEARCH_ACCESS = "SEARCH-ACCESS"
const val PARA_SEARCH_COUNT = "SEARCH-COUNT"
const val PARA_SEARCH_TYPE = "SEARCH-TYPE"
const val PARAM_LANGUAGE = "Language"
const val PARAM_GENRE = "Genre"
const val PARA_POSITION = "POSITION"
const val PARA_FILTER_LANGUAGE = "FILTER-LANGUAGE"
const val PARA_FILTER_GENRE = "FILTER-GENRE"
const val ALL_CONTENT_STATE = "ALL CONTENT"
const val FREE_STATE = "FREE"

const val PARA_CLICK_POSITION = "CLICK-POSITION"
const val PARA_TITLE = "TITLE"
const val PARA_SUGGESTOR_TYPE = "SUGGESTOR-TYPE"
const val PARA_CONTENT_ID = "CONTENT-ID"
const val PARA_MATCHES = "MATCHES"
const val PARA_MATCH_COUNT = "MATCH-COUNT"


/*Search Values*/
const val VOICE_SEARCH = "Voice"
const val VOICE = "VOICE"
const val RECENT_SEARCH = "Recent Search"
const val AUTO_COMPLETE = "Auto-Complete"
const val MANUAL = "Manual"
const val ALL = "All"
const val TEXT = "Text"

/*Profile Events*/
/*Profile Parameters*/
const val PARA_PROFILE_NAME = "PROFILE-NAME"
/*Profile Values*/
const val REGULAR ="Regular"

/*Notification Screen Events Parameters*/
const val PARA_ENABLE_NOTIFICATION="ENABLE-NOTIFICATION"

const val TRUE="TRUE"
const val FALSE="FALSE"

/*Add Pack Screen Events Parameters*/
const val PARA_SUBSCRIBE_FAILURE_REASON = "FAILURE-REASON"
const val PARA_PACK_NAME = "PACK-NAME"
const val PARA_PACK_PRICE = "PACK-PRICE"
const val PARA_MOD_TYPE = "MOD-TYPE"
const val PARA_PACK_TYPE = "PACK-TYPE"
const val PARA_BINGE_CANCEL_ON = "BINGE-RAISED-ON"
const val PARA_PRIME_CANCEL_ON = "PRIME-RAISED-ON"
const val PARA_BINGE_CANCEL_DATE = "BINGE-CANCELLATION-DATE"
const val PARA_PRIME_CANCEL_DATE = "PRIME-CANCELLATION-DATE"
const val PARA_BINGE_CANCELLATION = "BINGE-CANCELLATION"
const val PARA_PRIME_CANCELLATION = "PRIME-CANCELLATION"
const val PARA_REVOKED_ON = "REVOKED-ON"
const val PARA_SUBSCRIPTION_DRAWER_CLOSE = "SUBSCRIPTION-DRAWER-CLOSE"

//PACK-SELECTION
const val PARA_PAYMENT_METHOD = "PAYMENT-METHOD"
const val PARA_PAYMENT_TYPE = "PAYMENT-TYPE"
const val PARA_DURATION = "DURATION"
const val PARA_CHANGE_PLAN = "CHANGE-PLAN"
const val PARA_CHANGE_TENURE = "CHANGE-TENURE"
const val PARA_PAYABLE_AMOUNT = "PAYABLE-AMOUNT"


//MY-PLAN-VIEW
const val PARA_PACK_ACTIVE = "PACK-ACTIVE"
const val PARA_PRIME_PACK_ACTIVE = "PRIME-PACK-ACTIVE"

//MY-PLAN-RENEW-PLAN
const val PARA_DAYS_REMAINING = "DAYS-REMAINING"


const val ONLINE = "ONLINE"
const val OFFLINE = "OFFLINE"

/*Add Pack Screen Events Parameters*/
const val PARA_DURATION_SECONDS = "DURATION-SECONDS"
const val PARA_INITIAL_BUFFER_DURATION_SECONDS = "INITIAL-BUFFER-TIME-SECONDS"
const val PARA_DURATION_MINUTES = "DURATION-MINUTES"
const val PARA_INITIAL_BUFFER_DURATION_MINUTES = "INITIAL-BUFFER-DURATION-MINUTES"
const val PARA_START_TIME = "START-TIME"
const val PARA_STOP_TIME = "STOP-TIME"
const val PARA_NO_OF_PAUSE = "NUMBER-OF-PAUSE"
const val PARA_NO_OF_RESUME = "NUMBER-OF-RESUME"
const val PERCENTAGE = "PERCENTAGE"
const val CONTENT_TITLE = "CONTENT-TITLE"
const val PARENT_TITLE = "PARENT-TITLE"
const val CONTENT_GENRE = "CONTENT-GENRE"
const val CONTENT_TYPE = "CONTENT-TYPE"
const val CONTENT_LANGUAGE = "CONTENT-LANGUAGE"
const val PLAYING_MODE = "PLAYING-MODE"
const val PROVIDER = "PROVIDER"


//GAMES PARAMETERES
const val PARA_GAME_GENRE = "GAME-GENRE"
const val PARA_GAME_PARTNER = "GAME-PARTNER"
const val PARA_GAME_POSITION = "GAME-POSITION"
const val PARA_GAME_RATING = "GAME-RATING"
const val PARA_GAME_TITLE = "GAME-TITLE"
const val PARA_FREE_GAME = "FREE-GAME"
const val PARA_GAME_TYPE = "GAME-TYPE"
const val PARA_RAIL_GENRE_POSITION = "RAIL-GENRE-SELECTED"
const val PARA_GENRE_SELECTED = "GENRE-SELECTED"
const val PARA_PAGE_RESULT_SWIPE = "PAGE-RESULT-SWIPE"
const val DEFAULT_SOURCE = "other"
const val PARA_GAME_RAIL_GENERE_POSITION = "RAIL-GENRE-POSITION"

//GAMES EVENTS
const val EVENT_GAME_CLICK = "GAME-CLICK"
const val EVENT_GAME_PLAY_FAIL = "GAME-PLAY-FAIL"
const val EVENT_GAME_BROWSE_BY_GENRE_RAIL_CLICK = "GAME-BROWSE-BY-GENRE-RAIL-CLICK"
const val EVENT_ADD_FAVOURITE = "GAME-ADD-FAVOURITE"
const val EVENT_REMOVE_FAVOURITE = "GAME-REMOVE-FAVOURITE"

/*Source for Genre and language*/
const val EVENT_VALUE_SOURCE_APPS       = "APPS"
const val EVENT_VALUE_SOURCE_GENRE       = "BROWSE-BY-GENRE"
const val EVENT_VALUE_SOURCE_LANGUAGE    = "BROWSE-BY-LANGUAGE"
const val EVENT_VALUE_RAIL_HB    = "HERO-BANNER"
const val EVENT_VALUE_SOURCE_DETAIL    = "Content-Detail"
const val EVENT_VALUE_SEE_ALL    = "See-All"
const val EVENT_VALUE_CONTINUE_WATCHING    = "CONTINUE-WATCHING"


const val PARA_PACKAGE_TYPE = "PACKAGE-TYPE"
const val PARA_ACTION = "ACTION"

/* Player Playback Error Parameters */
const val PARA_ERROR_CODE = "ERROR-CODE"
const val PARA_ERROR_MESSAGE = "ERROR-MESSAGE"
const val PARA_ERROR_TYPE_GENERAL = "GENERAL"
const val PARA_ERROR_TYPE_API = "API"
const val PARA_ERROR_TYPE_PLAYER = "PLAYER"
const val PARA_ERROR_TYPE_SDK = "SDK"
const val PARA_PI_ERROR_ORIGIN = "PI_PAGE"


/* Misc Parameter */
const val PARA_DAY = "DAY"
const val PARA_USERSTATE = "USER-STATE"
const val PARA_CONTENT_PARENT_TITLE = "CONTENT-PARENT-TITLE"
const val PARA_AUTO_PLAYED = "AUTO-PLAYED"
const val FREE_TRIAL_STARTED="FREETRIALSTARTED"
const val FREEMIUM="FREEMIUM"
const val TENURE = "TENURE"
const val APPLAUNCH = "APP-LAUNCH"
const val NUDGE = "NUDGE"
const val OPTION = "OPTION"
const val MENU_BOTTOM = "MENU-BOTTOM"
const val GAME_PAGE_VISITED = "GAME-PAGE-VISITED"
const val CATEGORIES = "CATEGORIES"
const val MENU_CATEGORY = "MENU-CATEGORY"
const val CATEGORY_NAME = "CATEGORY-NAME"
const val PACK_TENURE = "PACK-TENURE"
const val EXISTING_PACK_NAME = "EXISTING-PACK-NAME"
const val EXISTING_PACK_TYPE = "EXISTING-PACK-TYPE"
const val EXISTING_PACK_PRICE = "EXISTING-PACK-PRICE"
const val EXISTING_PACK_TENURE = "EXISTING-PACK-TENURE"
const val FIRST_SUBSCRIPTION = "FIRST-SUBSCRIPTION"
const val PAYMENT_INITIATE = "PAYMENT-INITIATE"
const val SUBSCRIPTION_INITIATE = "SUBSCRIPTION-INITIATE"
const val USER_TYPE = "USER-TYPE"
const val USER_TYPE_TP = "TP"
const val USER_TYPE_NON_DTH = "NON-TP"
const val USER_TYPE_GUEST = "GUEST"
const val TSWALLET = "TSWALLET"
const val PG = "PG"
const val ONETIME = "ONETIME"
const val RECURRING = "RECURRING"
const val OPEL_ONE_TIME = "OPEL_ONE_TIME"
const val OPEL_RECURRING = "OPEL_RECURRING"
const val COMPLETED = "COMPLETED"
const val FAILED = "Failed"
const val ERROR = "ERROR"
const val ERROR_CODE = "ERROR-CODE"
const val KEY_IS_FIRST_SUBSCRIPTION = "isFirstPaidPack"
const val SOURCE_LOGIN_UPPER="LOGIN"
const val DBR="DBR"
const val MBR="MBR"
const val DEVICEMANAGEMENT="DeviceManagement"
const val DOWNGRADE="DOWNGRADE"
const val FORGOT_PIN="FORGOT PIN"
const val SETUP_PIN="SETUP PIN"
const val CHANGE_PIN="CHANGE PIN"
const val FRESH="FRESH"
const val UPGRADE="UPGRADE"
const val RENEW="RENEW"
const val DIY="DIY"
const val FSD="FSD"
const val RESULT_PAGE="Result Page"
const val SEARCH_PAGE="Search Page"
const val GO_VIP="GOVIP"
const val SWITCHSUBSCRIPTION="SWITCHSUBSCRIPTION"
const val HC_HAMBURGER_CLICK = "HC-HAMBURGER-CLICK"
const val PACK_MOD_TYPE = "PACK-MOD-TYPE"
const val SUBSCRIBE_TYPE = "SUBSCRIBE-TYPE"
const val NEW = "NEW"
const val REPEAT = "REPEAT"
const val MODIFY_PACK = "MODIFY-PACK"
const val PREVUSED = "PREVUSED"
const val TP_WALLET = "TP-WALLET"
const val PAYMENT_GATEWAY = "PAYMENT-GATEWAY"
const val COACH_MARK_DISPLAYED = "COACH-MARK-DISPLAYED"
const val COACH_MARK_ICON_CLICK = "COACH-MARK-ICON-CLICK"
const val COACH_MARK_OUTSIDE_CLICK = "COACH-MARK-OUTSIDE-CLICK"
const val COACH_MARK_NAME = "COACH-MARK-NAME"
const val DISPLAY_COUNT = "DISPLAY-COUNT"
const val REVENUE = "REVENUE"
const val DRAWER_MYOP="DRAWER#MYOP"
const val DRAWER_CYOP="DRAWER#CYOP"
const val MYPLAN_CHANGE ="MYPLAN#CHANGE"
const val MYPLAN_REGIONAL ="MYPLAN#REGIONAL"
const val HOME_CONTENT ="HOME#CONTENT"
const val SCREEN_PLAN ="SCREEN#PLAN"
const val MYPLAN_TENURE ="MYPLAN#TENURE"
const val CURATED_PACK_SELECTION="curated-pack-selection"
const val CONTENT_PLAY="content-play"
const val MYPLAN_EDIT =" my-plan-edit"
const val TICK_NUDGE ="nudge"
const val TATAPLAY = "TATAPLAY"
const val SEARCH_SUGGESTION = "SEARCH-SUGGESTIONS"