package com.tatasky.binge.ui.features.home

enum class ItemLayoutType {
    LANDSCAPE,
    PORTRAIT,//PORTRAIT
    APP_RAIL,
    GENRE,
    LANGUAGE,
    CATEGORY,
    CIRCULAR,
    GENRE_LANDSCAPE,
    GENRE_GAMES,
    TOP_PORTRAIT,
    POPULAR_CHARACTER,
    MIXED,
    MIXED_WITH_PROVIDER_DATA,
    TITLE_RAIL,
    MID_SCROLL_RAIL,
    GENRE_RAIL_FOR_GAMES,
    SQUARE,
    BINGE_CHANNEL,
    SINGLE_PROVIDER_BANNER_RAIL
}
