package com.tatasky.binge.ui.features.player.listeners;
 //Created by Varun Mishra on 8/8/18.
/**
 * This is used for the callback of RRM DeviceId and RRM Error to Activity
 */
public interface DeviceRegistrationListener {
       /**
        * @param deviceId provide the deviceID generated by player
        */
       void onDeviceIdReceived(String deviceId);

       /**
        * @param rrmError provide the Player Error form RRM
        */
       void onRRMError(String rrmError);
}
